{
 "title": "Compliance Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Top Devices with Failed Checks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "compliance_results",
     "rawSql": "SELECT device, COUNT(status) FROM compliance_results.results WHERE status = 'FAIL' GROUP BY device ORDER BY COUNT(status) DESC LIMIT 10 "
    }
   ]
  },
  {
   "title": "Rule Pass/Fail Percentage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "compliance_results",
     "rawSql": "select rulename, sum(case when status = 'PASS' then 1 else 0 end) as pass, sum(case when status = 'FAIL' then 1 else 0 end) as fail from results where $__timeFilter(time) group by rulename; "
    }
   ]
  },
  {
   "title": "Passed Checks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "compliance_results",
     "rawSql": "select count(*) from compliance_results.results where status = 'PASS' and $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Failed Checks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "compliance_results",
     "rawSql": "select count(*) from compliance_results.results where status = 'FAIL' and $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Rule Pass/Fail Summary",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "compliance_results",
     "rawSql": "select rulename, sum(case when status = 'PASS' then 1 else 0 end) as pass, sum(case when status = 'FAIL' then 1 else 0 end) as fail from results where $__timeFilter(time) group by rulename; "
    }
   ]
  },
  { "title": "Rule Results Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Results",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "compliance_results",
     "rawSql": "select * from results where $__timeFilter(time) "
    }
   ]
  }
 ]
}